after_script:
- make odoo-stop
before_script:
- "wget https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip"
- "mkdir chromedriver"
- "sudo unzip chromedriver_linux64.zip -d chromedriver"
- "export PATH=$PATH:chromedriver"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3  # give xvfb some time to start
- make odoo-start
env:
- TOXENV=py27
- TOXENV=flake8
- TOXENV=readme
install:
- make develop
language: python
script:
- make test
services:
- docker
sudo: required
